### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jrsconfitto**
Supersedes #20

### CODE REVIEW

**Comment by xavierdecoster** [comment]
Thanks! :)

**Comment by jrsconfitto** [comment]
👍🏻

**Comment by yishaigalatzer** [comment]
@xavierdecoster @jugglingnutcase this repo is no longer relevant. Sorry for the trouble.

The code has long moved out of here (as indicated on the front page).

We are currently moving the code (again :( ) to nuget.client, and it should be open for PRs hopefully by end of week or early next week.

**Comment by jrsconfitto** [comment]
Oops! My mistake.

**Pull request merged**
